/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  EntityModelExampleModel,
  ExampleModelRequestBody,
  PagedModelEntityModelExampleModel,
} from '../models';
import {
    EntityModelExampleModelFromJSON,
    EntityModelExampleModelToJSON,
    ExampleModelRequestBodyFromJSON,
    ExampleModelRequestBodyToJSON,
    PagedModelEntityModelExampleModelFromJSON,
    PagedModelEntityModelExampleModelToJSON,
} from '../models';

export interface DeleteItemResourceExamplemodelDeleteRequest {
    id: string;
}

export interface GetCollectionResourceExamplemodelGet1Request {
    page?: number;
    size?: number;
    sort?: Array<string>;
}

export interface GetItemResourceExamplemodelGetRequest {
    id: string;
}

export interface PatchItemResourceExamplemodelPatchRequest {
    id: string;
    exampleModelRequestBody: ExampleModelRequestBody;
}

export interface PostCollectionResourceExamplemodelPostRequest {
    exampleModelRequestBody: ExampleModelRequestBody;
}

export interface PutItemResourceExamplemodelPutRequest {
    id: string;
    exampleModelRequestBody: ExampleModelRequestBody;
}

/**
 * 
 */
export class ExampleModelEntityControllerApi extends runtime.BaseAPI {

    /**
     * delete-examplemodel
     */
    async deleteItemResourceExamplemodelDeleteRaw(requestParameters: DeleteItemResourceExamplemodelDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling deleteItemResourceExamplemodelDelete.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/exampleModels/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * delete-examplemodel
     */
    async deleteItemResourceExamplemodelDelete(requestParameters: DeleteItemResourceExamplemodelDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteItemResourceExamplemodelDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * get-examplemodel
     */
    async getCollectionResourceExamplemodelGet1Raw(requestParameters: GetCollectionResourceExamplemodelGet1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PagedModelEntityModelExampleModel>> {
        const queryParameters: any = {};

        if (requestParameters.page !== undefined) {
            queryParameters['page'] = requestParameters.page;
        }

        if (requestParameters.size !== undefined) {
            queryParameters['size'] = requestParameters.size;
        }

        if (requestParameters.sort) {
            queryParameters['sort'] = requestParameters.sort;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/exampleModels`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PagedModelEntityModelExampleModelFromJSON(jsonValue));
    }

    /**
     * get-examplemodel
     */
    async getCollectionResourceExamplemodelGet1(requestParameters: GetCollectionResourceExamplemodelGet1Request = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PagedModelEntityModelExampleModel> {
        const response = await this.getCollectionResourceExamplemodelGet1Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * get-examplemodel
     */
    async getItemResourceExamplemodelGetRaw(requestParameters: GetItemResourceExamplemodelGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EntityModelExampleModel>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling getItemResourceExamplemodelGet.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/exampleModels/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EntityModelExampleModelFromJSON(jsonValue));
    }

    /**
     * get-examplemodel
     */
    async getItemResourceExamplemodelGet(requestParameters: GetItemResourceExamplemodelGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EntityModelExampleModel> {
        const response = await this.getItemResourceExamplemodelGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * patch-examplemodel
     */
    async patchItemResourceExamplemodelPatchRaw(requestParameters: PatchItemResourceExamplemodelPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EntityModelExampleModel>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling patchItemResourceExamplemodelPatch.');
        }

        if (requestParameters.exampleModelRequestBody === null || requestParameters.exampleModelRequestBody === undefined) {
            throw new runtime.RequiredError('exampleModelRequestBody','Required parameter requestParameters.exampleModelRequestBody was null or undefined when calling patchItemResourceExamplemodelPatch.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/exampleModels/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: ExampleModelRequestBodyToJSON(requestParameters.exampleModelRequestBody),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EntityModelExampleModelFromJSON(jsonValue));
    }

    /**
     * patch-examplemodel
     */
    async patchItemResourceExamplemodelPatch(requestParameters: PatchItemResourceExamplemodelPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EntityModelExampleModel> {
        const response = await this.patchItemResourceExamplemodelPatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * create-examplemodel
     */
    async postCollectionResourceExamplemodelPostRaw(requestParameters: PostCollectionResourceExamplemodelPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EntityModelExampleModel>> {
        if (requestParameters.exampleModelRequestBody === null || requestParameters.exampleModelRequestBody === undefined) {
            throw new runtime.RequiredError('exampleModelRequestBody','Required parameter requestParameters.exampleModelRequestBody was null or undefined when calling postCollectionResourceExamplemodelPost.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/exampleModels`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ExampleModelRequestBodyToJSON(requestParameters.exampleModelRequestBody),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EntityModelExampleModelFromJSON(jsonValue));
    }

    /**
     * create-examplemodel
     */
    async postCollectionResourceExamplemodelPost(requestParameters: PostCollectionResourceExamplemodelPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EntityModelExampleModel> {
        const response = await this.postCollectionResourceExamplemodelPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * update-examplemodel
     */
    async putItemResourceExamplemodelPutRaw(requestParameters: PutItemResourceExamplemodelPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EntityModelExampleModel>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling putItemResourceExamplemodelPut.');
        }

        if (requestParameters.exampleModelRequestBody === null || requestParameters.exampleModelRequestBody === undefined) {
            throw new runtime.RequiredError('exampleModelRequestBody','Required parameter requestParameters.exampleModelRequestBody was null or undefined when calling putItemResourceExamplemodelPut.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/exampleModels/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: ExampleModelRequestBodyToJSON(requestParameters.exampleModelRequestBody),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EntityModelExampleModelFromJSON(jsonValue));
    }

    /**
     * update-examplemodel
     */
    async putItemResourceExamplemodelPut(requestParameters: PutItemResourceExamplemodelPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EntityModelExampleModel> {
        const response = await this.putItemResourceExamplemodelPutRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
