/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { EntityModelExampleModel } from './EntityModelExampleModel';
import {
    EntityModelExampleModelFromJSON,
    EntityModelExampleModelFromJSONTyped,
    EntityModelExampleModelToJSON,
} from './EntityModelExampleModel';

/**
 * 
 * @export
 * @interface PagedModelEntityModelExampleModelEmbedded
 */
export interface PagedModelEntityModelExampleModelEmbedded {
    /**
     * 
     * @type {Array<EntityModelExampleModel>}
     * @memberof PagedModelEntityModelExampleModelEmbedded
     */
    exampleModels?: Array<EntityModelExampleModel>;
}

/**
 * Check if a given object implements the PagedModelEntityModelExampleModelEmbedded interface.
 */
export function instanceOfPagedModelEntityModelExampleModelEmbedded(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PagedModelEntityModelExampleModelEmbeddedFromJSON(json: any): PagedModelEntityModelExampleModelEmbedded {
    return PagedModelEntityModelExampleModelEmbeddedFromJSONTyped(json, false);
}

export function PagedModelEntityModelExampleModelEmbeddedFromJSONTyped(json: any, ignoreDiscriminator: boolean): PagedModelEntityModelExampleModelEmbedded {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'exampleModels': !exists(json, 'exampleModels') ? undefined : ((json['exampleModels'] as Array<any>).map(EntityModelExampleModelFromJSON)),
    };
}

export function PagedModelEntityModelExampleModelEmbeddedToJSON(value?: PagedModelEntityModelExampleModelEmbedded | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'exampleModels': value.exampleModels === undefined ? undefined : ((value.exampleModels as Array<any>).map(EntityModelExampleModelToJSON)),
    };
}

