/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Link } from './Link';
import {
    LinkFromJSON,
    LinkFromJSONTyped,
    LinkToJSON,
} from './Link';
import type { PageMetadata } from './PageMetadata';
import {
    PageMetadataFromJSON,
    PageMetadataFromJSONTyped,
    PageMetadataToJSON,
} from './PageMetadata';
import type { PagedModelEntityModelExampleModelEmbedded } from './PagedModelEntityModelExampleModelEmbedded';
import {
    PagedModelEntityModelExampleModelEmbeddedFromJSON,
    PagedModelEntityModelExampleModelEmbeddedFromJSONTyped,
    PagedModelEntityModelExampleModelEmbeddedToJSON,
} from './PagedModelEntityModelExampleModelEmbedded';

/**
 * 
 * @export
 * @interface PagedModelEntityModelExampleModel
 */
export interface PagedModelEntityModelExampleModel {
    /**
     * 
     * @type {PagedModelEntityModelExampleModelEmbedded}
     * @memberof PagedModelEntityModelExampleModel
     */
    embedded?: PagedModelEntityModelExampleModelEmbedded;
    /**
     * 
     * @type {{ [key: string]: Link; }}
     * @memberof PagedModelEntityModelExampleModel
     */
    links?: { [key: string]: Link; };
    /**
     * 
     * @type {PageMetadata}
     * @memberof PagedModelEntityModelExampleModel
     */
    page?: PageMetadata;
}

/**
 * Check if a given object implements the PagedModelEntityModelExampleModel interface.
 */
export function instanceOfPagedModelEntityModelExampleModel(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PagedModelEntityModelExampleModelFromJSON(json: any): PagedModelEntityModelExampleModel {
    return PagedModelEntityModelExampleModelFromJSONTyped(json, false);
}

export function PagedModelEntityModelExampleModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): PagedModelEntityModelExampleModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'embedded': !exists(json, '_embedded') ? undefined : PagedModelEntityModelExampleModelEmbeddedFromJSON(json['_embedded']),
        'links': !exists(json, '_links') ? undefined : (mapValues(json['_links'], LinkFromJSON)),
        'page': !exists(json, 'page') ? undefined : PageMetadataFromJSON(json['page']),
    };
}

export function PagedModelEntityModelExampleModelToJSON(value?: PagedModelEntityModelExampleModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        '_embedded': PagedModelEntityModelExampleModelEmbeddedToJSON(value.embedded),
        '_links': value.links === undefined ? undefined : (mapValues(value.links, LinkToJSON)),
        'page': PageMetadataToJSON(value.page),
    };
}

