/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Link } from './Link';
import {
    LinkFromJSON,
    LinkFromJSONTyped,
    LinkToJSON,
} from './Link';

/**
 * 
 * @export
 * @interface RepresentationModelObject
 */
export interface RepresentationModelObject {
    /**
     * 
     * @type {{ [key: string]: Link; }}
     * @memberof RepresentationModelObject
     */
    links?: { [key: string]: Link; };
}

/**
 * Check if a given object implements the RepresentationModelObject interface.
 */
export function instanceOfRepresentationModelObject(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function RepresentationModelObjectFromJSON(json: any): RepresentationModelObject {
    return RepresentationModelObjectFromJSONTyped(json, false);
}

export function RepresentationModelObjectFromJSONTyped(json: any, ignoreDiscriminator: boolean): RepresentationModelObject {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'links': !exists(json, '_links') ? undefined : (mapValues(json['_links'], LinkFromJSON)),
    };
}

export function RepresentationModelObjectToJSON(value?: RepresentationModelObject | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        '_links': value.links === undefined ? undefined : (mapValues(value.links, LinkToJSON)),
    };
}

